language: java

jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --no-tty --no-use-agent --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install: true
script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
    provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: Hevelian/hevelian-activemq
      jdk: oraclejdk8
